### ISSUE TITLE
Allow for use of pure JS p5 files without having to change any code

### ISSUE THREAD

**Issue by VirtualParticle** [RowanACM/game_project#8]
It might be easier to allow front-end developers to program in pure JS without having to worry about all of the react stuff. Then all of the sketch files could just be placed in the p5 folder.

**Comment by ElvinT57** [comment]
This would be perfect. Will this be possible with our current environment?

**Comment by VirtualParticle** [comment]
I'm trying to figure out a way to do this. One way is to simply serve the files statically in the public directory of the project, but that's unnecessarily giving the client files they may not need or perhaps should not have access to. I'm pretty sure there's also a way to simply embed `<script>` tags in react components which would also work,  but apparently this is frowned upon, given the delightful name "dangerouslySetInnerHtml". If there's not a good way to do it we could just go with that option. It can get tedious converting normal p5 sketches to node components so finding a way to do this would be good.

**Comment by jasonharrison** [comment]
Switched to Phaser
